# Generated by Django 3.0 on 2022-07-28 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.TextField()),
                ('owner', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('eststate_list', models.TextField(blank=True, default='')),
                ('websocket_url', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('sender_name', models.TextField()),
                ('receiver_name', models.TextField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('description', models.TextField(default=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_owner', to='chat.Contacts')),
            ],
        ),
        migrations.AddField(
            model_name='contacts',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_msg', to='chat.Messages'),
        ),
    ]
