# Generated by Django 3.0 on 2022-08-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20220817_1249'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contacts',
            unique_together={('contact', 'owner')},
        ),
    ]
