# Generated by Django 3.0 on 2022-08-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_user_is_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
