# Generated by Django 3.0 on 2022-08-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='rent_status',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
