# Generated by Django 3.0 on 2022-08-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20220818_1809'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estate',
            unique_together={('estate_type', 'estate_status', 'area', 'society')},
        ),
    ]
