# Generated by Django 3.0 on 2022-08-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20220826_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='broker_mobile',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='estate',
            name='broker_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
